
#####################
### Elasticsearch ###
#####################

elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
elasticsearch_hostname: es01
elasticsearch_conf_dir: /usr/share/elasticsearch


#####################
### Kibana ###
#####################

kibana_image: docker.elastic.co/elasticsearch/kibana:7.13.3
kibana_hostname: ki01

#####################
### logstash ###
#####################

logstash_image: docker.elastic.co/elasticsearch/logstash:7.13.3
logstash_hostname: lo01
logstash_conf_dir: /usr/share/logstash
